version: 2

builds:
  - goos:
      - darwin
    goarch:
      - arm64
    ldflags:
      - -s -w -X github.com/zeke-john/komplete/cmd.Version={{.Version}}

archives:
  - formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"

homebrew_casks:
  - repository:
      owner: zeke-john
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    homepage: "https://github.com/zeke-john/komplete"
    description: "AI shell assistant - natural language to commands and inline autocomplete"
    binaries:
      - komplete
    caveats: |
      Get started:
        komplete config set openrouter_api_key YOUR_KEY

      Optional alias, add to .zshrc:
        alias k=komplete

      Optional autocomplete, add to .zshrc:
        komplete config set groq_api_key YOUR_KEY
      Then run: komplete init zsh

changelog:
  use: git
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
