version: 2

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X github.com/zeke-john/komplete/cmd.Version={{.Version}}

archives:
  - formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"

homebrew_casks:
  - repository:
      owner: zeke-john
      name: homebrew-tap
    homepage: "https://github.com/zeke-john/komplete"
    description: "AI shell assistant - natural language to commands and inline autocomplete"
    binaries:
      - komplete
    hooks:
      post:
        install: |
          if OS.mac?
            system_command ""/usr/bin/xattr"", args: [""-dr"", ""com.apple.quarantine"", ""#{staged_path}/komplete""]
          end
    caveats: |
      Set your API key to start using komplete:

        komplete config set openrouter_api_key YOUR_KEY

      Optional alias (add to .zshrc):

        eval "$(komplete init alias)"

      Optional inline autocomplete (add to .zshrc):

        eval "$(komplete init zsh)"
        komplete config set groq_api_key YOUR_KEY

changelog:
  use: github
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
