// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ go get github.com/boundaryml/baml
//
// ----------------------------------------------------------------------------

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ go install github.com/boundaryml/baml/baml-cli

package type_builder

import baml "github.com/boundaryml/baml/engine/language_client_go/pkg"

type CommandClassView struct {
	inner baml.ClassBuilder
}

func (t *CommandClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *CommandClassView) PropertyCmd() (ClassPropertyView, error) {
	return t.inner.Property("cmd")
}

func (t *CommandClassView) PropertyRationale() (ClassPropertyView, error) {
	return t.inner.Property("rationale")
}

func (t *TypeBuilder) Command() (*CommandClassView, error) {
	bld, err := t.inner.Class("Command")
	if err != nil {
		return nil, err
	}
	return &CommandClassView{inner: bld}, nil
}

func (t *CommandClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type PlanClassView struct {
	inner baml.ClassBuilder
}

func (t *PlanClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *PlanClassView) PropertySummary() (ClassPropertyView, error) {
	return t.inner.Property("summary")
}

func (t *PlanClassView) PropertyCommands() (ClassPropertyView, error) {
	return t.inner.Property("commands")
}

func (t *TypeBuilder) Plan() (*PlanClassView, error) {
	bld, err := t.inner.Class("Plan")
	if err != nil {
		return nil, err
	}
	return &PlanClassView{inner: bld}, nil
}

func (t *PlanClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}
