// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ go get github.com/boundaryml/baml
//
// ----------------------------------------------------------------------------

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ go install github.com/boundaryml/baml/baml-cli

package stream_types

import (
	"fmt"

	baml "github.com/boundaryml/baml/engine/language_client_go/pkg"
	"github.com/boundaryml/baml/engine/language_client_go/pkg/cffi"
)

type Command struct {
	Cmd       *string `json:"cmd"`
	Rationale *string `json:"rationale"`
}

func (c *Command) Decode(holder *cffi.CFFIValueClass, typeMap baml.TypeMap) {
	typeName := holder.Name
	if typeName.Namespace != cffi.CFFITypeNamespace_STREAM_TYPES {
		panic(fmt.Sprintf("expected cffi.CFFITypeNamespace_STREAM_TYPES, got %s", string(typeName.Namespace.String())))
	}
	if typeName.Name != "Command" {
		panic(fmt.Sprintf("expected Command, got %s", typeName.Name))
	}

	for _, field := range holder.Fields {
		key := field.Key
		valueHolder := field.Value
		switch key {

		case "cmd":
			c.Cmd = baml.Decode(valueHolder).Interface().(*string)

		case "rationale":
			c.Rationale = baml.Decode(valueHolder).Interface().(*string)

		default:

			panic(fmt.Sprintf("unexpected field: %s in class Command", key))

		}
	}

}

func (c Command) Encode() (*cffi.HostValue, error) {
	fields := map[string]any{}

	fields["cmd"] = c.Cmd

	fields["rationale"] = c.Rationale

	return baml.EncodeClass("Command", fields, nil)
}

func (c Command) BamlTypeName() string {
	return "Command"
}

type Plan struct {
	Summary  *string   `json:"summary"`
	Commands []Command `json:"commands"`
}

func (c *Plan) Decode(holder *cffi.CFFIValueClass, typeMap baml.TypeMap) {
	typeName := holder.Name
	if typeName.Namespace != cffi.CFFITypeNamespace_STREAM_TYPES {
		panic(fmt.Sprintf("expected cffi.CFFITypeNamespace_STREAM_TYPES, got %s", string(typeName.Namespace.String())))
	}
	if typeName.Name != "Plan" {
		panic(fmt.Sprintf("expected Plan, got %s", typeName.Name))
	}

	for _, field := range holder.Fields {
		key := field.Key
		valueHolder := field.Value
		switch key {

		case "summary":
			c.Summary = baml.Decode(valueHolder).Interface().(*string)

		case "commands":
			c.Commands = baml.Decode(valueHolder).Interface().([]Command)

		default:

			panic(fmt.Sprintf("unexpected field: %s in class Plan", key))

		}
	}

}

func (c Plan) Encode() (*cffi.HostValue, error) {
	fields := map[string]any{}

	fields["summary"] = c.Summary

	fields["commands"] = c.Commands

	return baml.EncodeClass("Plan", fields, nil)
}

func (c Plan) BamlTypeName() string {
	return "Plan"
}
