// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ go get github.com/boundaryml/baml
//
// ----------------------------------------------------------------------------

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ go install github.com/boundaryml/baml/baml-cli

package baml_client

var file_map = map[string]string{

	"clients.baml":    "client<llm> OpenRouter {\n  provider openai-generic\n  options {\n    base_url \"https://openrouter.ai/api/v1\"\n    api_key env.OPENROUTER_API_KEY\n    model \"anthropic/claude-haiku-4.5\"\n  }\n}\n\nclient<llm> OpenAI {\n  provider openai\n  retry_policy Exponential\n  options {\n    model \"gpt-4o-mini\"\n    api_key env.OPENAI_API_KEY\n  }\n}\n\nclient<llm> Anthropic {\n  provider anthropic\n  retry_policy Exponential\n  options {\n    model \"claude-haiku-4.5\"\n    api_key env.ANTHROPIC_API_KEY\n  }\n}\n\nretry_policy Exponential {\n  max_retries 2\n  strategy {\n    type exponential_backoff\n    delay_ms 300\n    multiplier 1.5\n    max_delay_ms 10000\n  }\n}\n",
	"generators.baml": "// This helps use auto generate libraries you can use in the language of\n// your choice. You can have multiple generators if you use multiple languages.\n// Just ensure that the output_dir is different for each generator.\ngenerator target {\n    // Valid values: \"python/pydantic\", \"typescript\", \"go\", \"rust\", \"ruby/sorbet\", \"rest/openapi\"\n    output_type \"go\"\n\n    // Where the generated code will be saved (relative to baml_src/)\n    output_dir \"../\"\n\n    // The version of the BAML package you have installed (e.g. same version as your baml-py or @boundaryml/baml).\n    // The BAML VSCode extension version should also match this version.\n    version \"0.218.1\"\n\n    // 'baml-cli generate' will run this after generating go code\n    // This command will be run from within $output_dir/baml_client\n    on_generate \"gofmt -w . && goimports -w .\"\n\n    // Your Go packages name as specified in go.mod\n    // We need this to generate correct imports in the generated baml_client\n    client_package_name \"github.com/zeke-john/komplete\"\n}\n",
	"komplete.baml":   "class Plan {\n  summary string\n  commands Command[]\n}\n\nclass Command {\n  cmd string\n  rationale string\n}\n\nfunction GeneratePlan(user_request: string, os: string, shell: string, cwd: string, repo_root: string, git_status: string) -> Plan {\n  client \"OpenRouter\"\n  prompt #\"\n    You are a senior developer who types shell commands for the user. When they describe what they want, you give them the exact commands they would type.\n\n    Your job is simple: translate what the user wants into shell commands. Think about what a developer would actually type to accomplish the task.\n\n    Rules:\n    - NEVER refuse. Every request maps to commands.\n    - Give real, working commands that run as-is.\n    - Be direct and minimal. No extra steps.\n    - If something could be destructive, mention it in the summary but still give the commands.\n    - Use the context provided (OS, shell, current directory) to give appropriate commands.\n    - IMPORTANT: The user will run each command you provide. Do NOT give multiple variations or alternatives of the same command. Pick the single best and most commonly used command for each distinct task. For example, if they want a git diff, give ONE git diff command, not three variations.\n\n    Context:\n    - OS: {{ os }}\n    - Shell: {{ shell }}\n    - Current directory: {{ cwd }}\n    - Git repo root: {{ repo_root }}\n    - Git status: {{ git_status }}\n\n    User wants: \"{{ user_request }}\"\n\n    {{ ctx.output_format }}\n  \"#\n}\n\n// Basic test example. Run in the BAML playground if needed.\ntest komplete_plan_example {\n  functions [GeneratePlan]\n  args {\n    user_request #\"list files in this folder\"#\n    os #\"darwin\"#\n    shell #\"zsh\"#\n    cwd #\"/Users/example/project\"#\n    repo_root #\"/Users/example/project\"#\n    git_status #\"clean on main\"#\n  }\n}\n",
}

func getBamlFiles() map[string]string {
	return file_map
}
