// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ go get github.com/boundaryml/baml
//
// ----------------------------------------------------------------------------

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ go install github.com/boundaryml/baml/baml-cli

package baml_client

import (
	"context"
	"fmt"

	baml "github.com/boundaryml/baml/engine/language_client_go/pkg"
	"github.com/zeke-john/komplete/baml_client/types"
)

func GeneratePlan(ctx context.Context, user_request string, os string, shell string, cwd string, repo_root string, git_status string, command_history string, opts ...CallOptionFunc) (types.Plan, error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	// Resolve client option to clientRegistry (client takes precedence)
	if callOpts.client != nil {
		if callOpts.clientRegistry == nil {
			callOpts.clientRegistry = baml.NewClientRegistry()
		}
		callOpts.clientRegistry.SetPrimaryClient(*callOpts.client)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"user_request": user_request, "os": os, "shell": shell, "cwd": cwd, "repo_root": repo_root, "git_status": git_status, "command_history": command_history},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		panic(err)
	}

	if callOpts.onTick == nil {
		result, err := bamlRuntime.CallFunction(ctx, "GeneratePlan", encoded, callOpts.onTick)
		if err != nil {
			return types.Plan{}, err
		}

		if result.Error != nil {
			return types.Plan{}, result.Error
		}

		casted := (result.Data).(types.Plan)

		return casted, nil
	} else {
		channel, err := bamlRuntime.CallFunctionStream(ctx, "GeneratePlan", encoded, callOpts.onTick)
		if err != nil {
			return types.Plan{}, err
		}

		for result := range channel {
			if result.Error != nil {
				return types.Plan{}, result.Error
			}

			if result.HasData {
				return result.Data.(types.Plan), nil
			}
		}

		return types.Plan{}, fmt.Errorf("No data returned from stream")
	}
}
