// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ go get github.com/boundaryml/baml
//
// ----------------------------------------------------------------------------

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ go install github.com/boundaryml/baml/baml-cli

package baml_client

import (
	"reflect"

	"github.com/zeke-john/komplete/baml_client/stream_types"
	"github.com/zeke-john/komplete/baml_client/types"
)

var typeMap = map[string]reflect.Type{
	"TYPES.Command":        reflect.TypeOf(types.Command{}),
	"STREAM_TYPES.Command": reflect.TypeOf(stream_types.Command{}),
	"TYPES.Plan":           reflect.TypeOf(types.Plan{}),
	"STREAM_TYPES.Plan":    reflect.TypeOf(stream_types.Plan{}),
}
